# Generated by Django 4.0.4 on 2022-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_promotions_guid_one_c_alter_promotions_data_sync_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
