# Generated by Django 4.0.4 on 2022-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_promotions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuses',
            name='data_sync',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sync date with other app'),
        ),
    ]
