# Generated by Django 4.0.4 on 2022-04-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Company')),
                ('activity', models.BooleanField(default=True, verbose_name='Аctivity')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_key', models.CharField(max_length=200, verbose_name='Param key')),
                ('param_val', models.TextField(blank=True, verbose_name='Date end of action')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Config data',
                'verbose_name_plural': 'Config',
            },
        ),
    ]
