# Generated by Django 4.0.4 on 2022-04-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.IntegerField(verbose_name='Id Telegram')),
                ('mention', models.CharField(max_length=200, verbose_name='Mention')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('user_name', models.CharField(max_length=200, verbose_name='User name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Company')),
            ],
        ),
    ]
