# Generated by Django 4.0.4 on 2022-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_configdata_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='Аctivity'),
        ),
    ]
