# Generated by Django 4.0.4 on 2022-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='Approval to the processing of personal data'),
        ),
    ]
