# Generated by Django 4.0.4 on 2022-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='User name'),
        ),
    ]
