# Generated by Django 4.0.4 on 2022-05-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='create_1c',
            field=models.BooleanField(default=False, verbose_name='Created in the 1C program'),
        ),
    ]
